# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Common 17-41} -limit 10000000

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param simulator.modelsimInstallPath C:/modeltech64_10.5/win64
  set_param xicom.use_bs_reader 1
  create_project -in_memory -part xc7a100tcsg324-1
  set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.cache/wt [current_project]
  set_property parent.project_path F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.xpr [current_project]
  set_property ip_output_repo F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.runs/synth_1/ARMSOC_TOP_with_busmatrix.dcp
  read_ip -quiet F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.srcs/sources_1/ip/fifo_for_dma_cxy/fifo_for_dma_cxy.xci
  read_ip -quiet F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.srcs/sources_1/ip/mult_for_cnn_cxy/mult_for_cnn_cxy.xci
  read_ip -quiet F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.srcs/sources_1/ip/fifo_for_dcmi/fifo_for_dcmi.xci
  read_ip -quiet F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.srcs/sources_1/ip/bram_for_vga/bram_for_vga.xci
  read_ip -quiet F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.srcs/sources_1/ip/bram_for_vga_cam/bram_for_vga_cam.xci
  read_xdc F:/Prj2020/Vivado/NexysA7_fullsystem_rebuild_0727/NexysA7_fullsystem_rebuild_0727.srcs/constrs_1/imports/constraints/NexysA7.xdc
  link_design -top ARMSOC_TOP_with_busmatrix -part xc7a100tcsg324-1
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force ARMSOC_TOP_with_busmatrix_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file ARMSOC_TOP_with_busmatrix_drc_opted.rpt -pb ARMSOC_TOP_with_busmatrix_drc_opted.pb -rpx ARMSOC_TOP_with_busmatrix_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  implement_debug_core 
  place_design 
  write_checkpoint -force ARMSOC_TOP_with_busmatrix_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file ARMSOC_TOP_with_busmatrix_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file ARMSOC_TOP_with_busmatrix_utilization_placed.rpt -pb ARMSOC_TOP_with_busmatrix_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file ARMSOC_TOP_with_busmatrix_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force ARMSOC_TOP_with_busmatrix_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file ARMSOC_TOP_with_busmatrix_drc_routed.rpt -pb ARMSOC_TOP_with_busmatrix_drc_routed.pb -rpx ARMSOC_TOP_with_busmatrix_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file ARMSOC_TOP_with_busmatrix_methodology_drc_routed.rpt -pb ARMSOC_TOP_with_busmatrix_methodology_drc_routed.pb -rpx ARMSOC_TOP_with_busmatrix_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file ARMSOC_TOP_with_busmatrix_power_routed.rpt -pb ARMSOC_TOP_with_busmatrix_power_summary_routed.pb -rpx ARMSOC_TOP_with_busmatrix_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file ARMSOC_TOP_with_busmatrix_route_status.rpt -pb ARMSOC_TOP_with_busmatrix_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file ARMSOC_TOP_with_busmatrix_timing_summary_routed.rpt -rpx ARMSOC_TOP_with_busmatrix_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file ARMSOC_TOP_with_busmatrix_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file ARMSOC_TOP_with_busmatrix_clock_utilization_routed.rpt"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force ARMSOC_TOP_with_busmatrix_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force ARMSOC_TOP_with_busmatrix.mmi }
  write_bitstream -force ARMSOC_TOP_with_busmatrix.bit 
  catch {write_debug_probes -quiet -force ARMSOC_TOP_with_busmatrix}
  catch {file copy -force ARMSOC_TOP_with_busmatrix.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

